<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FakeItEasy" Version="9.0.1" />
        <PackageReference Include="FakeItEasy.Analyzer.CSharp" Version="6.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
      <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
      <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
      <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\FuncPipeline\FuncPipeline.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <DebugType>full</DebugType>
    </PropertyGroup>

</Project>
