name: Build, Test, Publish

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"
      - "*.png" 
      - "*.drawio" 
      - ".gitignore"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"
      - "*.png" 
      - "*.drawio" 
      - ".gitignore" 

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      id-token: write
      contents: read
      checks: write  

    steps:
 
    - uses: actions/checkout@v3

    - id: set-version
      name: Set Version
      run: |
        if ${IS_TAG} == true; then
          version=$(echo ${{ github.ref }} | cut -c 11-)
          echo "VERSION=$version" >> $GITHUB_ENV          
        else
          version="$(date +'%Y').$(date +'%m').$(date +'%d').$(date +'%H%M')"
          echo "VERSION=$version" >> $GITHUB_ENV
        fi

    - id: print-version
      name: Print Version
      run: |
        echo "is tag: $IS_TAG"
        echo "version: ${{ env.VERSION }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore EventBrokerSlim.sln

    - name: Build
      run: dotnet build EventBrokerSlim.sln --no-restore --configuration Release -p:Version=${{ env.VERSION }}

    - name: Run Unit Tests
      run: dotnet test test/M.EventBrokerSlim.Tests/M.EventBrokerSlim.Tests.csproj --no-build --no-restore --verbosity normal --configuration Release --logger trx --collect:"XPlat Code Coverage" --results-directory testresults

    - name: Unit Tests Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests Report
        path: testresults/*.trx
        reporter: dotnet-trx

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: testresults/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'