name: Build, Test, Publish

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "EventBrokerSlim/ReadMe.md"
      - "EventBrokerSlim/package-icon.png" 
      - "FuncPipeline/ReadMe.md"
      - ".gitignore"
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "EventBrokerSlim/ReadMe.md"
      - "EventBrokerSlim/package-icon.png" 
      - "FuncPipeline/ReadMe.md"
      - ".gitignore" 

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write  

    steps:
 
    - uses: actions/checkout@v4

    - id: set-version
      name: Set Version
      run: |
        ref=${{ github.ref }}
        pattern="^refs/tags/(EventBrokerSlim|FuncPipeline)_v([0-9]+.[0-9]+.[0-9]+(-.+)?)$"
        
        if [[ $ref =~ $pattern ]]; then
          is_release=true
          version=${BASH_REMATCH[2]}
          project=${BASH_REMATCH[1]}
        else
          is_release=false
          version="0.0.1-build$(date +'%Y%m%d'-'%H%M%S')"
        fi  
        
        echo "IS_RELEASE=$is_release" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "PROJECT=$project" >> $GITHUB_ENV

    - id: print-version
      name: Print Version
      run: |
        echo "is release:  ${{ env.IS_RELEASE }}"
        echo "version: ${{ env.VERSION }}"
        echo "project: ${{ env.PROJECT }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore EventBrokerSlim.sln

    - name: Build
      run: dotnet build EventBrokerSlim.sln --no-restore --configuration Release -p:Version=${{ env.VERSION }}

    - name: Run Unit Tests EventBrokerSlim net8.0
      run: dotnet test EventBrokerSlim/test/M.EventBrokerSlim.Tests/M.EventBrokerSlim.Tests.csproj -f net8.0 --no-build --no-restore --verbosity normal --configuration Release --logger trx --collect:"XPlat Code Coverage" --results-directory testresults

    - name: Run Unit Tests EventBrokerSlim net9.0
      run: dotnet test EventBrokerSlim/test/M.EventBrokerSlim.Tests/M.EventBrokerSlim.Tests.csproj -f net9.0 --no-build --no-restore --verbosity normal --configuration Release --logger trx --collect:"XPlat Code Coverage" --results-directory testresults

    - name: Run Unit Tests FuncPipeline net8.0
      run: dotnet test FuncPipeline/test/FuncPipeline.Tests/FuncPipeline.Tests.csproj -f net8.0 --no-build --no-restore --verbosity normal --configuration Release --logger trx --collect:"XPlat Code Coverage" --results-directory testresults

    - name: Run Unit Tests FuncPipeline net9.0
      run: dotnet test FuncPipeline/test/FuncPipeline.Tests/FuncPipeline.Tests.csproj -f net9.0 --no-build --no-restore --verbosity normal --configuration Release --logger trx --collect:"XPlat Code Coverage" --results-directory testresults

    - name: Install Markdown Test Report Tool
      if: success() || failure()
      run: dotnet tool install --global LiquidTestReports.Cli --version 2.0.0-beta.6

    - name: Generate Markdown Test Report
      if: success() || failure()
      run: liquid --inputs "File=**/*.trx;Format=Trx" --output-file testresults/testresults.md --title "Unit Tests"

    - name: Output Unit Tests Summary
      if: success() || failure()
      run: |
        summary=$(<"testresults/testresults.md")
        echo "$summary" >> "$GITHUB_STEP_SUMMARY"

    - name: Unit Tests Code Coverage Report
      if: success() || failure()  
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: "**/coverage.cobertura.xml"
        targetdir: "coveragereport"
        reporttypes: "MarkdownSummaryGithub"
        verbosity: "Info"
        title: "Unit Tests Code Coverage"
        toolpath: "reportgeneratortool"

    - name: Output Code Coverage Summary
      if: success() || failure()
      run: |
        summary=$(<"coveragereport/SummaryGithub.md")
        echo "$summary" >> "$GITHUB_STEP_SUMMARY"

    - name: Create NuGet Package for EventBrokerSlim
      if: ${{ success() && env.IS_RELEASE == 'true' && env.PROJECT == 'EventBrokerSlim' }}    
      run: dotnet pack EventBrokerSlim/src/M.EventBrokerSlim/M.EventBrokerSlim.csproj -p:PackageVersion=${{ env.VERSION }} --output ./ --configuration Release --no-restore --no-build  -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    
    - name: Create NuGet Package for FuncPipeline
      if: ${{ success() && env.IS_RELEASE == 'true' && env.PROJECT == 'FuncPipeline' }}    
      run: dotnet pack FuncPipeline/src/FuncPipeline/FuncPipeline.csproj -p:PackageVersion=${{ env.VERSION }} --output ./ --configuration Release --no-restore --no-build  -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    
    - name: Publish NuGet Package
      if: ${{ success() && env.IS_RELEASE == 'true' }}    
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_API }} -s https://api.nuget.org/v3/index.json
